<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3967e5ca-f9d5-4035-ace2-5437c235c09f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
    <ProjectReference Include="..\..\WordleGameEngine\WordleGameEngine.csproj" />
  </ItemGroup>

</Project>
